REPORT_STATUS_DRAFT = "draft"
REPORT_STATUS_LOCAL_ONLY = "local_only"
REPORT_STATUS_READY_FOR_REVIEW = "ready_for_review"
REPORT_STATUS_TRIAGED = "triaged"
REPORT_STATUS_INFO_ONLY = "info_only"
REPORT_STATUS_PENDING_SUBMISSION = "pending_submission"
REPORT_STATUS_SUBMITTED = "submitted"
REPORT_STATUS_RECEIVED = "received"
REPORT_STATUS_WITHDRAWN = "withdrawn"
REPORT_STATUS_CLOSED = "closed"
REPORT_STATUS_DELETED = "deleted"

REPORT_STATUSES = {
    REPORT_STATUS_DRAFT,
    REPORT_STATUS_LOCAL_ONLY,
    REPORT_STATUS_READY_FOR_REVIEW,
    REPORT_STATUS_TRIAGED,
    REPORT_STATUS_INFO_ONLY,
    REPORT_STATUS_PENDING_SUBMISSION,
    REPORT_STATUS_SUBMITTED,
    REPORT_STATUS_RECEIVED,
    REPORT_STATUS_WITHDRAWN,
    REPORT_STATUS_CLOSED,
    REPORT_STATUS_DELETED,
}

SEVERITIES = {"low", "medium", "high", "critical"}
ANONYMITY_MODES = {"identified", "anonymous", "pseudonymous"}

SUBMISSION_STATUS_DRAFT_PREVIEW = "draft_preview"
SUBMISSION_STATUS_QUEUED = "queued"
SUBMISSION_STATUS_SUBMITTED = "submitted"
SUBMISSION_STATUS_ACKNOWLEDGED = "acknowledged"
SUBMISSION_STATUS_REQUIRES_MANUAL_ACTION = "requires_manual_action"
SUBMISSION_STATUS_CONFIG_MISSING = "config_missing"
SUBMISSION_STATUS_WITHDRAWN = "withdrawn"
SUBMISSION_STATUS_FAILED = "failed"

ACTIVE_SUBMISSION_STATUSES = {
    SUBMISSION_STATUS_QUEUED,
    SUBMISSION_STATUS_SUBMITTED,
    SUBMISSION_STATUS_ACKNOWLEDGED,
    SUBMISSION_STATUS_REQUIRES_MANUAL_ACTION,
    SUBMISSION_STATUS_CONFIG_MISSING,
}

WITHDRAW_BLOCKED_STATUSES = {
    REPORT_STATUS_SUBMITTED,
    REPORT_STATUS_RECEIVED,
    REPORT_STATUS_CLOSED,
    REPORT_STATUS_DELETED,
}

STRUCTURED_FIELD_KEYS = {
    "who",
    "what",
    "when",
    "where",
    "how",
    "witnesses",
    "repeatedIncidents",
    "injuries",
    "supportMessage",
    "evidenceItems",
}
